import { motion } from "framer-motion";
import { FaRobot, FaMapMarkedAlt, FaUserFriends, FaShieldAlt, FaDollarSign, FaClock } from "react-icons/fa";

const Features = () => {
  const features = [
    {
      icon: <FaRobot className="text-4xl" />,
      title: "AI-Powered Planning",
      description: "Get personalized travel itineraries generated by advanced AI based on your preferences and budget.",
      gradient: "from-purple-500 to-pink-500"
    },
    {
      icon: <FaMapMarkedAlt className="text-4xl" />,
      title: "120+ Destinations",
      description: "Explore curated destinations worldwide with insider tips and hidden gems from local experts.",
      gradient: "from-blue-500 to-cyan-500"
    },
    {
      icon: <FaUserFriends className="text-4xl" />,
      title: "Expert Local Guides",
      description: "Connect with verified local guides who bring authentic experiences and deep local knowledge.",
      gradient: "from-green-500 to-teal-500"
    },
    {
      icon: <FaShieldAlt className="text-4xl" />,
      title: "Safe & Secure",
      description: "Travel with confidence knowing all guides are verified and bookings are protected.",
      gradient: "from-orange-500 to-red-500"
    },
    {
      icon: <FaDollarSign className="text-4xl" />,
      title: "Best Price Guarantee",
      description: "Get the best deals with transparent pricing and flexible budget options for every traveler.",
      gradient: "from-yellow-500 to-orange-500"
    },
    {
      icon: <FaClock className="text-4xl" />,
      title: "24/7 Support",
      description: "Our dedicated support team is always available to assist you throughout your journey.",
      gradient: "from-indigo-500 to-purple-500"
    }
  ];

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1
      }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: {
      opacity: 1,
      y: 0,
      transition: { duration: 0.5 }
    }
  };

  return (
    <section className="py-16 md:py-24 bg-gradient-to-b from-gray-50 to-white">
      <div className="container mx-auto px-4 md:px-6 lg:px-12">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <span className="text-blue-600 font-semibold text-sm md:text-base uppercase tracking-wider">Why Choose Us</span>
          <h2 className="text-3xl md:text-5xl font-bold mt-4 mb-6">
            Everything You Need for the{" "}
            <span className="bg-gradient-to-r from-blue-600 to-teal-500 bg-clip-text text-transparent">
              Perfect Journey
            </span>
          </h2>
          <p className="text-gray-600 text-lg max-w-2xl mx-auto">
            We've built the ultimate travel platform combining cutting-edge technology with human expertise
          </p>
        </motion.div>

        {/* Features Grid */}
        <motion.div
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true }}
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8"
        >
          {features.map((feature, index) => (
            <motion.div
              key={index}
              variants={itemVariants}
              whileHover={{ y: -10, transition: { duration: 0.3 } }}
              className="group relative bg-white rounded-2xl p-8 shadow-lg hover:shadow-2xl transition-all duration-300 border border-gray-100"
            >
              {/* Icon Container */}
              <div
                className={`inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-to-br ${feature.gradient} text-white mb-6 group-hover:scale-110 transition-transform duration-300`}
              >
                {feature.icon}
              </div>

              {/* Content */}
              <h3 className="text-xl font-bold text-gray-900 mb-3">
                {feature.title}
              </h3>
              <p className="text-gray-600 leading-relaxed">
                {feature.description}
              </p>

              {/* Hover Effect Border */}
              <div className={`absolute inset-0 rounded-2xl bg-gradient-to-br ${feature.gradient} opacity-0 group-hover:opacity-10 transition-opacity duration-300`}></div>
            </motion.div>
          ))}
        </motion.div>

        {/* Bottom CTA */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ delay: 0.5 }}
          className="text-center mt-16"
        >
          <button className="px-8 py-4 bg-gradient-to-r from-blue-600 to-teal-500 text-white rounded-full font-semibold text-lg shadow-lg hover:shadow-2xl transition-all duration-300 hover:scale-105">
            Start Your Adventure Today
          </button>
        </motion.div>
      </div>
    </section>
  );
};

export default Features;
